export const ADD_USERS = "ADD_USERS";
export const SHOW_POPUP = "SHOW_POPUP";
export const HIDE_POPUP = "HIDE_POPUP";
export const UPDATE_USER_DETAILS = "UPDATE_USER_DETAILS";
export const UPDATE_FOLLOWERS_DETAILS = "UPDATE_FOLLOWERS_DETAILS";
